### ISSUE TITLE
DSA <什么是算法> 翻译建议 

### ISSUE THREAD

**Issue by relic-yuexi** [apachecn/programiz-zh#1]
原文为:
> Qualities of a good algorithm

您的翻译为 

>好的算法的质量

个人建议:

>一个好算法应有的4个条件

还有第四点

原文:

>An algorithm shouldn't include computer code. Instead, the algorithm should be written in such a way that it can be used in different programming languages.

您的翻译为:

>算法不应该包含计算机代码。 相反，应以可以在不同编程语言中使用的方式编写算法。（这里有点不通顺）

个人建议:

>一个算法描述不应该用一种编程语言描述。相反，算法应该以一种能够在不同编程语言实现的形式来描述。（例如伪代码）

我也不是专业的，如有不顺，还望见谅。

**Comment by wizardforcel** [comment]
请提PR，谢谢
